### ISSUE TITLE
Cannot play Search command

### ISSUE THREAD

**Issue by Nich87** [Nich87/Discord-Musicbot#3]
`
Error: Unable to find a id in "h"
    at AsyncFunction.main.getPlaylistID (/home/runner/reikajs/node_modules/ytpl/lib/main.js:224:11)
    at module.exports (/home/runner/reikajs/node_modules/ytpl/lib/main.js:13:30)
    at play_request (/home/runner/reikajs/index.js:116:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/home/runner/reikajs/index.js:59:20)
`
ytplのバグか不明ですがytpl.validateID()でbooleanが返ってこないため再生出来ない。

**Comment by Nich87** [comment]
暫定的にplaylistという単語を見つけたらplaylistとして読み込むように変更しました。
近日中に正規表現にてチェックするように変更致します。

**Comment by Nich87** [comment]
自分の関数の呼び出しによる**自己のミス**でした。
